name       : ccsm
version    : 0.8.16
release    : 2
source     :
    - https://gitlab.com/compiz/ccsm/-/archive/v0.8.16/ccsm-v0.8.16.tar.bz2 : 7c579402255f48f19b1b20824ed5364b423ef973603284ef0632ac612f7da3bc
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : CompizConfig Settings Manager
rundeps    :
    - compiz
    - compizconfig-python
    - compiz-plugins-main
    - compiz-plugins-extra
description: |
    A graphical manager for CompizConfig Plugin (libcompizconfig).
build      : |
    %python3_setup
install    : |
    %python3_install --prefix=/usr
